services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq-uenf
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: senha_segura
    volumes:
      - rabbitmq-uenf-data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq

  postgres:
    image: postgres:16
    container_name: postgres-uenf
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: redis-uenf
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  rustfs:
    image: rustfs:latest
    container_name: rustfs-uenf
    restart: unless-stopped
    environment:
      RUSTFS_ACCESS_KEY: user
      RUSTFS_SECRET_KEY: password
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  rabbitmq_data:
  rabbitmq_log:
  postgres_data:
  redis-data:
    drver: local
